---
- hosts: "{{ hosts_string | default('linoder') }}"
  become: true
  remote_user: root
  tasks:
    - name: Install python3-pip - Debian 11
      apt:
        name:
          - python3-pip
          - python3-venv
        update_cache: yes
        state: present

    - name: Install AWS-CLI via PIP - Debian 11
      pip:
        name: awscli
        version: "1.22.55"
        state: present
        virtualenv: "/opt/aws-cli"
